- name: Install development packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - "@Development Tools"
      - android-tools
      - cargo
      - g++
      - hexedit
      - openssl-devel
      - perf
      - readline-devel
      - SDL2_ttf-devel
      - SDL2-devel
      - strace
      - valgrind
      - wayland-devel
      - wlroots-devel

- name: Install development flatpaks
  community.general.flatpak:
    name:
      - com.visualstudio.code-oss
      - io.qt.QtCreator