- name: Install theming packages
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - fontawesome4-fonts
      - papirus-icon-theme

- name: Install papirus folders script
  become: yes
  ansible.builtin.shell: wget -qO- https://git.io/papirus-folders-install | sh
  args:
    creates: /usr/share/icons/Papirus